name: Upload Release Build

on:
  release:
    types: [published]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: Create directory
        run: cd ..; mkdir ./builds

      # Zip the source code
      - name: Zip Source
        run: zip -r ../builds/Source.zip *

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Create build directory
      - name: Create build directory
        run: mkdir ./builds

      # Build for Firefox and Chrome
      - name: Build for Firefox
        run: npx extension build --browser firefox --polyfill
      - name: Build for Chrome
        run: npx extension build --browser chrome --polyfill

      - name: Sign and Publish artifact
        continue-on-error: true
        env:
          FIREFOX_ISSUER: ${{ secrets.FIREFOX_ISSUER }}
          FIREFOX_SECRET: ${{ secrets.FIREFOX_SECRET }}
        run: npx web-ext sign --channel listed -s ./dist/firefox/ --upload-source-code  ../builds/Source.zip --artifacts-dir ./dist/firefox --api-key $FIREFOX_ISSUER --api-secret $FIREFOX_SECRET --amo-metadata ./firefox-metadata.json --approval-timeout 0

      - name: Zip Chrome Artifacts
        run: cd ./dist/chrome ; zip -r ../../builds/ChromeExtension.zip *
      - name: Upload ChromeExtension to release
        uses: Shopify/upload-to-release@07611424e04f1475ddf550e1c0dd650b867d5467
        with:
          name: ChromeExtension.zip
          path: ./builds/ChromeExtension.zip
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish to Chrome Web Store
        continue-on-error: true
        uses: wdzeng/chrome-extension@v1
        with:
          client-id: ${{ secrets.CHROME_CLIENT_ID }}
          client-secret: ${{ secrets.CHROME_CLIENT_SECRET }}
          refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}
          zip-path: ./builds/ChromeExtension.zip
          extension-id: npdpncicgllbfbobialabnmbbkfkdpio
